DFT Engine:
  Engine: PySCF
  Memory (MB): 16000.0
  Threads: '4'
  DFTB+ Settings:
    D3(BJ) Dispersion Correction: false
    Partial Charge Method: CM3
  Psi4 Settings:
    Basis: def2-SVP
    D3(BJ) Dispersion Correction: false
    Functional: wB97X
    Geometry Convergence: normal
    Partial Charge Method: ESP
    Preoptimization: None
    SCF Convergence: normal
  PySCF Settings:
    Basis: def2-SVP
    Functional: M06-2X
    Partial Charge Method: No Charges
    gridsize: 1
    Preoptimization: DFTB
    td_opts_override: {conv_tol: 1.0E-6, level_shift: 0.5, deg_eia_thresh: 1.0E-2, max_cycle = 300}
    td_grad_override: {cphf_conv_tol: 1.0E-6, cphf_max_cycle: 300}
    geomeTRIC_override: {coordsys: tric, maxiter: 100, trust: 0.33333}
    Geometry Convergence: TURBOMOLE
    tda: False
    mf: {level_shift: 0.5, conv_tol: 1.0E-8}
  Turbomole Settings:
    Basis: def2-SVP
    D3(BJ) Dispersion Correction: false
    Functional: B3LYP
    Geometry Convergence: normal
    Partial Charge Method: ESP
    Preoptimization: None
    SCF Convergence: normal
    static_polarizability: false
  XTB Settings:
    GFN: '2'
    Geometry Convergence: normal
    Optimization Cycles: '2000'
    Partial Charge Method: CM5
  w_fit:
    do_w_fit: false
    fit_to: EA
    guess_w: normal
    no_cosmo: false
    target_value: 0.0
Molecule Settings:
  Calculate UV/VIS spectrum: false
  Charge: 0
  Excited State of Interest: 1
  Molecule (Mol2): molecule_S0_opt.mol2
  Molecule Identifier: F6L
  Multiplicity: '1'
  Optimize Molecule: false
  Parameter File: default
