calculatorId: mobility_calculator
files:
- files_for_kmc.zip
image: diadem.azurecr.io/mobility_small:0.0.1
onDemandEnabled: true
poolId: Standard_D4_v3
price: 50
provides:
- mobility
specification:
  QPParametrizer:
    DFT Engine:
      Threads: '30'
      Engine: Psi4
      Memory (MB): 78000.0
      PySCF Settings:
        basis: def2-SVP
  DihedralParametrizer:
    DFT_options:
      Basis: def2-SVP
      Engine: PySCF
      memory_per_thread: 4000
    DH_scan_steps: 180
    forcefield_optimization:
        no_samples: 1000
        scf_iter: 1
        version: v4
  Deposit:
    simparams:
      Nmol: 1000
      PBC: True
      sa:
        steps: 130000
      postrelaxation_steps: 10000
    Box:
      Lx: 50.0
      Ly: 50.0
      Lz: 180.0
      grid_overhang: 30
  QuantumPatch:
    QuantumPatch:
      calculateJs: true
      qpproxJs: true
      morphology: structurePBC.cml
      partial_charge_cutoff: 60
    System:
      Core:
        number: 200
      Shells:
        '0':
          cutoff: 15.0
        '1':
          cutoff: 60.0
        '2':
          cutoff: 25.0
  lightforge:
    morphology_width: 40
    layers:
      - thickness: 40
    experiments:
      - simulations: 10
        Temperature: 300
        field_strength: 0.02 0.03 0.04
    iv_fluctuation: 0.05
    max_iterations: 5000000
version: 1.0.0
