DFT Engine:
  Engine: PySCF
  Memory (MB): 16000.0
  Threads: '4'
  DFTB+ Settings:
    D3(BJ) Dispersion Correction: false
    Partial Charge Method: CM3
  Psi4 Settings:
    Basis: def2-SVP
    D3(BJ) Dispersion Correction: false
    Functional: wB97X
    Geometry Convergence: normal
    Partial Charge Method: ESP
    Preoptimization: None
    SCF Convergence: normal
  PySCF Settings:
    Basis: def2-SVPD
    Functional: PBE0
    D3(BJ) Dispersion Correction: false
    Partial Charge Method: No Charges
    gridsize: fast
    Preoptimization: DFTB
    Geometry Convergence: pyscf
    mf: {level_shift: 0.5, conv_tol: 1.0E-7}
    cosmo: True
  Turbomole Settings:
    Basis: def2-SVP
    D3(BJ) Dispersion Correction: false
    Functional: B3LYP
    Geometry Convergence: normal
    Partial Charge Method: ESP
    Preoptimization: None
    SCF Convergence: normal
    static_polarizability: false
  XTB Settings:
    GFN: '2'
    Geometry Convergence: normal
    Optimization Cycles: '2000'
    Partial Charge Method: CM5
  w_fit:
    do_w_fit: false
    fit_to: EA
    guess_w: normal
    no_cosmo: false
    target_value: 0.0
Molecule Settings:
  Calculate UV/VIS spectrum: false
  Charge: 1
  Excited State of Interest: 0
  Molecule (Mol2): molecule_opt.mol2
  Molecule Identifier: F6L
  Multiplicity: '2'
  Optimize Molecule: false
  Parameter File: default
  deltaSCF: True