Analysis:
  Excitonic:
    Fluorescence:
      DFTEngine: Turbomole 1
      enabled: true
    Phosphorescence:
      DFTEngine: Dalton 1
      enabled: true
    TPQ:
      DFTEngine: Turbomole 1
      anion: true
      cation: true
      enabled: true
      roots: 20
    TTA:
      DFTEngine: Turbomole 1
      enabled: true
      roots: 20
  HigherOrder:
    ExtraJs: 7
  MachineLearning:
    enable: false
  MatrixEAIP:
    do_lambda: false
    radius: 15.0
  homo_lumo_generator:
    coulomb_cutoff: 25
    enabled: false
    esp_avrg_options:
      bins_per_nm: 1.7
      mode: by_distance
      z-extend: true
    non_PBC_morphology: structure.cml
    periodic_copies: [2, 2, 2]
    swap_x_z_axis: true
DFTEngine:
  defaults:
    DFTBplus:
      charge_model: cm3
      engine: DFTBplus
      threads: 1
    Dalton:
      basis: def2-SVP
      charge_model: ESP
      engine: Dalton
      functional: BP86
      memory: 1500
      threads: 1
    Psi4Engine:
      basis: def2-SVP
      charge_model: ESP
      engine: Psi4Engine
      functional: BP86
      memory: 1500
      reference: rdft
      threads: 1
    Turbomole:
      basis: def2-SVP
      charge_model: ESP
      engine: Turbomole
      functional: BP86
      memory: 1500
      threads: 1
  geo_opt:
    ffenv: true
    charge_model: cm3
    engine: DFTBplus
    threads: 1
  user:
    PySCF env:
      basis: def2-SVP
      charge_model: ESP
      engine: PySCF
      functional: BP86
      memory: 1500
      gridsize: fast
      mem_per_cpu: 3000
      threads: auto
      float_jk: true
    PySCF core:
      basis: def2-SVP
      charge_model: ESP
      engine: PySCF
      functional: B3LYP
      memory: 1500
      gridsize: fast
      mem_per_cpu: 3000
      threads: auto
      float_jk: true
    DFTB+ 1:
      charge_model: CM5
      dispersion: false
      engine: DFTBplus
      fallback: PySCF env
      memory: 1500
      threads: 1
QuantumPatch:
  calculateJs: true
  qpproxJs: true
  charge_damping: 0.15
  chargetype_multipoles: false
  dimer_cutoff: 7.0
  morphology: structurePBC.cml
  number_of_equilibration_steps: 7
  partial_charge_cutoff: 60
  type: uncharged_equilibration
  molstate_loop_order: null
System:
  Core:
    GeometricalOptimizationSteps: []
    default_molstates: 0;1
    engine: PySCF core
    engine_by_iter: {}
    number: 200
    type: number
  IdenticalMolecules:
    crystal_centers: []
    enable_mapping: false
    filename: identical_molecules.txt
  MolStates:
    '0':
      charge: 1
      excited_state_of_interest: 0
      multiplicity: 2
      roots: 0
    '1':
      charge: -1
      excited_state_of_interest: 0
      multiplicity: 2
      roots: 0
  Shells:
    '0':
      cutoff: 15.0
      engine: PySCF env
      engine_by_iter: {}
      type: scf
    '1':
      cutoff: 60.0
      engine: DFTB+ 1
      engine_by_iter: {}
      type: static
    '2':
      cutoff: 25.0
      engine: DFTB+ 1
      engine_by_iter: {}
      type: scf
